<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'Are you sure you want to delete this item?' => 'Tem certeza que deseja excluir este item?',
  'Delete' => 'Excluir',
  'Displaying {start}-{end} of {count} result(s).' => 'Exibindo {start}-{end} de {count} resultado(s).',
  'No' => 'Não',
  'No results found.' => 'Nenhum resultado encontrado.',
  'Not set' => 'Não definido',
  'Please specify the "attributes" property.' => 'Por favor, especifique o atributo "attributes".',
  'Please specify the "model" property.' => 'Por favor, especifique a propriedade "model".',
  'Sort by: ' => 'Ordenado por:',
  'The "dataProvider" property cannot be empty.' => 'A propriedade "dataProvider" não pode estar vazia.',
  'The attribute must be specified in the format of "Name:Type:Label", where "Type" and "Label" are optional.' => 'O atributo deve ser especificado no formato "Name:Type:Label", onde "Type" e "Label" são opcionais.',
  'The property "itemView" cannot be empty.' => 'A propriedade "itemView" não pode estar vazia.',
  'Total {count} result(s).' => 'Total {count} resultado(s)',
  'Unknown type "{type}".' => 'Tipo desconhecido "{type}".',
  'Update' => 'Editar',
  'View' => 'Visualizar',
  'Yes' => 'Sim',
  '{class} must specify "model" and "attribute" or "name" property values.' => '{class} deve especificar valores das propriedades "model" e "attribute" ou "name".',
);
